version: "3"

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todonextapi
volumes:
  db-data:

#サービス名を指定
#services: null
#dbとは、
#db:
  #environmentとは、コンテナの環境変数を設定する
  #environment:
  #  POSTGRES_DB: usernextapi
  #  POSTGRES_PASSWORD: root
  #  POSTGRES_USER: user
  #imageとは、docker hubから取得するイメージの名前
  #image: postgres
  #portsとは、ポートの設定、コンテナのポートとホストのポートを紐付ける
  #ports:
  #  - '5433:5432'
  #restartとは、コンテナの再起動設定
  #restart: always
  #volumesとは、コンテナのボリュームを設定する
  #volumes:
  #  - ./postgres:/var/lib/postgresql/data
#サービス名を指定
#services: null
#postgresqlで設定する
#version: '3.7'

#yamlの記法を守る、docker-composeも

#nest
#docker-composeの起動コマンド　docker-compose up -d
#postgresqlで設定する
#version: "3"

#サービス名を指定
#services: 
#dbとは、
#db:
  #environmentとは、コンテナの環境変数を設定する
  #environment:
    #POSTGRES_DB: todoNext
    #POSTGRES_PASSWORD: root
    #POSTGRES_USER: user4460
  #imageとは、docker hubから取得するイメージの名前
  #image: postgres
  #portsとは、ポートの設定、コンテナのポートとホストのポートを紐付ける
  #ports:
   # - 5432:5432
  #restartとは、コンテナの再起動設定
  #restart: always
  #volumesとは、コンテナのボリュームを設定する
  #volumes:
    #- db-data:/var/lib/postgresql/data