#dbとは、
db:
  #environmentとは、コンテナの環境変数を設定する
  environment:
    POSTGRES_DB: test
    POSTGRES_PASSWORD: root
    POSTGRES_USER: test
  #imageとは、docker hubから取得するイメージの名前
  image: postgres:12.2
  #portsとは、ポートの設定、コンテナのポートとホストのポートを紐付ける
  ports:
    - '5432:5432'
  #restartとは、コンテナの再起動設定
  restart: always
  #volumesとは、コンテナのボリュームを設定する
  volumes:
    - ./postgres:/var/lib/postgresql/data
#サービス名を指定
services: null
#postgresqlで設定する
version: '3.7'