#postgresqlで設定する
version: '3.7'
services:
db:
  image: postgres:12.2
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: root
    POSTGRES_USER: test
    POSTGRES_DB: test
  volumes:
    - ./postgres:/var/lib/postgresql/data
  restart: always

   